theme: jekyll-theme-cayman
description: The sweety animated responsive grid (with theme!)
avatar: https://yoandelmaire.fr/public/apple-icon-180x180.png
headline: Cherry.css

footer-links:
  email: ydelmaire@hotmail.com
  github: Rayzen-dev/cherry_css
